 export const travelersData = [
  {
  "id": 1,
  "name": "Sarah Johnson",
  "age": 28,
  "gender": "female",
  "rating": 4.8,
  "totalDeliveries": 47,
  "initialLocation": "New York, USA",
  "destination": "London, UK",
  "travelDate": "2025-11-05",
  "returnDate": "2025-11-12",
  "weight": "10-15",
  "description": "Frequent business traveler with extra luggage space. Very reliable and punctual.",
  "experience": "Traveled internationally for 5 years, carried packages for friends multiple times.",
  "avatar": "👩‍💼",
  "email": "sarah.johnson@email.com",
  "phone": "+1 (555) 123-4567",
  "amount": "1500-2500",
  "verified": true,
  "languages": ["English", "Spanish", "French"],
  "preferences": ["Electronics", "Documents", "Clothing"],
  "reviews": [
  { "id": 1, "sender": "John M.", "rating": 5, "comment": "Extremely reliable and delivered on time.", "date": "2025-09-25" }
  ]
  },
  {
  "id": 2,
  "name": "Kwame Nkrumah",
  "age": 35,
  "gender": "male",
  "rating": 4.5,
  "totalDeliveries": 32,
  "initialLocation": "Lagos, Nigeria",
  "destination": "Paris, France",
  "travelDate": "2025-11-20",
  "returnDate": "2025-12-01",
  "weight": "20-25",
  "description": "Traveling for a family visit and have a large, half-empty suitcase. Happy to help transport legal items.",
  "experience": "Regularly travels between West Africa and Europe, understands customs processes well.",
  "avatar": "👨‍🎨",
  "email": "kwame.nkrumah@mail.com",
  "phone": "+234 800 111 2222",
  "amount": "2000-3500",
  "verified": true,
  "languages": ["Yoruba", "English", "French"],
  "preferences": ["Textiles", "Small machinery", "Gifts"],
  "reviews": [
  { "id": 2, "sender": "Marie L.", "rating": 5, "comment": "Excellent communication and prompt delivery to Paris.", "date": "2025-10-10" }
  ]
  },
  {
  "id": 3,
  "name": "Luca Rossi",
  "age": 41,
  "gender": "male",
  "rating": 4.9,
  "totalDeliveries": 61,
  "initialLocation": "Berlin, Germany",
  "destination": "Rome, Italy",
  "travelDate": "2025-10-28",
  "returnDate": "2025-11-03",
  "weight": "5-10",
  "description": "Frequent inter-Europe traveler. Looking to cover part of travel expenses. Only small items accepted.",
  "experience": "Ten years of professional travel across the EU. Knows all air and rail delivery procedures.",
  "avatar": "👨‍💼",
  "email": "luca.rossi@travel.de",
  "phone": "+49 30 987 6543",
  "amount": "800-1500",
  "verified": true,
  "languages": ["German", "Italian", "English"],
  "preferences": ["Documents", "Small Gadgets", "Artwork"],
  "reviews": [
  { "id": 3, "sender": "Elena S.", "rating": 5, "comment": "Quick, efficient, and very professional service.", "date": "2025-09-01" }
  ]
  },
  {
  "id": 4,
  "name": "Maria Rodriguez",
  "age": 22,
  "gender": "female",
  "rating": 4.3,
  "totalDeliveries": 11,
  "initialLocation": "Mexico City, Mexico",
  "destination": "Madrid, Spain",
  "travelDate": "2025-12-10",
  "returnDate": "2025-12-24",
  "weight": "15-20",
  "description": "Student traveling home for the holidays. Extra capacity in checked bags. Flexible on drop-off times.",
  "experience": "Carried items for family between continents three times this year. New to the platform but reliable.",
  "avatar": "👩‍🎓",
  "email": "maria.r@stdnt.mx",
  "phone": "+52 55 2345 6789",
  "amount": "1800-3000",
  "verified": false,
  "languages": ["Spanish", "English"],
  "preferences": ["Books", "Clothing", "Personal gifts"],
  "reviews": [
  { "id": 4, "sender": "Ricardo G.", "rating": 4, "comment": "A bit slow on replies, but the item arrived safely and on time.", "date": "2025-10-05" }
  ]
  },
  {
  "id": 5,
  "name": "Aisha Omar",
  "age": 31,
  "gender": "female",
  "rating": 4.7,
  "totalDeliveries": 28,
  "initialLocation": "Cape Town, South Africa",
  "destination": "Amsterdam, Netherlands",
  "travelDate": "2026-01-15",
  "returnDate": "2026-01-29",
  "weight": "5-10",
  "description": "Short business trip, only carrying hand luggage. Can take small, high-value packages.",
  "experience": "Experienced in transporting fragile and time-sensitive documents across continents.",
  "avatar": "👩‍🔬",
  "email": "aisha.o@biznet.co.za",
  "phone": "+27 21 555 1212",
  "amount": "1200-2000",
  "verified": true,
  "languages": ["English", "Afrikaans", "Dutch"],
  "preferences": ["Jewelry", "Documents", "Tech accessories"],
  "reviews": [
  { "id": 5, "sender": "Dirk P.", "rating": 5, "comment": "Handled sensitive documents with great care. Highly recommended.", "date": "2025-10-20" }
  ]
  },
  {
  "id": 6,
  "name": "David Chen",
  "age": 48,
  "gender": "male",
  "rating": 4.6,
  "totalDeliveries": 88,
  "initialLocation": "Shanghai, China",
  "destination": "Los Angeles, USA",
  "travelDate": "2025-11-15",
  "returnDate": "2025-11-23",
  "weight": "10-15",
  "description": "Tech consultant flying to the US. Reliable and flexible on meeting times. Extra baggage space available.",
  "experience": "Over 50 international deliveries, excellent track record on customs declarations.",
  "avatar": "👨‍💻",
  "email": "david.chen@global.cn",
  "phone": "+86 21 8765 4321",
  "amount": "2500-4000",
  "verified": true,
  "languages": ["Mandarin", "English"],
  "preferences": ["Electronics", "Machine parts", "Samples"],
  "reviews": [
  { "id": 6, "sender": "Jeff K.", "rating": 4, "comment": "Package arrived a day early! Fast service.", "date": "2025-08-10" }
  ]
  },
  {
  "id": 7,
  "name": "Elias Tadesse",
  "age": 29,
  "gender": "male",
  "rating": 4.9,
  "totalDeliveries": 15,
  "initialLocation": "Addis Ababa, Ethiopia",
  "destination": "Dubai, UAE",
  "travelDate": "2025-12-01",
  "returnDate": "2025-12-07",
  "weight": "5-10",
  "description": "Short connection trip. Can carry small, urgent packages. Very secure.",
  "experience": "Regular flyer between the Middle East and East Africa. Prioritizes security.",
  "avatar": "🧑‍✈️",
  "email": "elias.t@ethio.com",
  "phone": "+251 91 100 0000",
  "amount": "900-1800",
  "verified": true,
  "languages": ["Amharic", "English", "Arabic"],
  "preferences": ["Documents", "Medicines", "Small items"],
  "reviews": [
  { "id": 7, "sender": "Fatima A.", "rating": 5, "comment": "Absolutely perfect service. Timely and trustworthy.", "date": "2025-10-25" }
  ]
  },
  {
  "id": 8,
  "name": "Chloe Lefevre",
  "age": 33,
  "gender": "female",
  "rating": 4.4,
  "totalDeliveries": 21,
  "initialLocation": "Paris, France",
  "destination": "Toronto, Canada",
  "travelDate": "2026-01-05",
  "returnDate": "2026-01-19",
  "weight": "15-20",
  "description": "Visiting family. Large empty space in luggage. Prefer non-fragile goods.",
  "experience": "Carried numerous items across the Atlantic for family and friends. Very organized.",
  "avatar": "👩‍🚀",
  "email": "chloe.l@travel.fr",
  "phone": "+33 6 12 34 56 78",
  "amount": "1700-2800",
  "verified": true,
  "languages": ["French", "English"],
  "preferences": ["Clothing", "Non-perishable food", "Books"],
  "reviews": [
  { "id": 8, "sender": "Ethan C.", "rating": 4, "comment": "Good service, received the package as described.", "date": "2025-09-15" }
  ]
  },
  {
  "id": 9,
  "name": "Javier Gomez",
  "age": 55,
  "gender": "male",
  "rating": 5.0,
  "totalDeliveries": 105,
  "initialLocation": "Buenos Aires, Argentina",
  "destination": "Rio de Janeiro, Brazil",
  "travelDate": "2025-11-01",
  "returnDate": "2025-11-04",
  "weight": "5-10",
  "description": "Short regional flight. Available for urgent small deliveries between these two cities only.",
  "experience": "Professional courier for 15 years, using this platform for side income.",
  "avatar": "👨‍🦳",
  "email": "javier.g@expresso.ar",
  "phone": "+54 11 9999 8888",
  "amount": "700-1300",
  "verified": true,
  "languages": ["Spanish", "Portuguese"],
  "preferences": ["Documents", "Keys", "Small Electronics"],
  "reviews": [
  { "id": 9, "sender": "Isabela F.", "rating": 5, "comment": "The fastest regional delivery I've ever used!", "date": "2025-10-15" }
  ]
  },
  {
  "id": 10,
  "name": "Priya Sharma",
  "age": 26,
  "gender": "female",
  "rating": 4.2,
  "totalDeliveries": 8,
  "initialLocation": "New Delhi, India",
  "destination": "Sydney, Australia",
  "travelDate": "2025-12-25",
  "returnDate": "2026-01-08",
  "weight": "20-30",
  "description": "Moving internationally and have significant extra baggage capacity. Willing to take large or heavy items.",
  "experience": "New to the platform but very organized and communicative. Long-haul flight experience.",
  "avatar": "👩‍🦱",
  "email": "priya.s@move.in",
  "phone": "+91 98765 00000",
  "amount": "3000-5000",
  "verified": false,
  "languages": ["Hindi", "English"],
  "preferences": ["Heavy items", "Tools", "Clothing"],
  "reviews": [
  { "id": 10, "sender": "Michael T.", "rating": 4, "comment": "Very courteous and helpful with a bulky package.", "date": "2025-10-01" }
  ]
  },
  {
  "id": 11,
  "name": "Ahmed Hassan",
  "age": 44,
  "gender": "male",
  "rating": 4.7,
  "totalDeliveries": 73,
  "initialLocation": "Cairo, Egypt",
  "destination": "Istanbul, Turkey",
  "travelDate": "2025-11-10",
  "returnDate": "2025-11-17",
  "weight": "5-10",
  "description": "Regular trader between these two regional hubs. Only small, low-risk items accepted.",
  "experience": "Decades of cross-border experience. Highly efficient and discreet.",
  "avatar": "👳‍♂️",
  "email": "ahmed.h@cairo.com",
  "phone": "+20 100 123 4567",
  "amount": "1000-1800",
  "verified": true,
  "languages": ["Arabic", "Turkish", "English"],
  "preferences": ["Documents", "Small machine parts", "Spices"],
  "reviews": [
  { "id": 11, "sender": "Ece Y.", "rating": 5, "comment": "Flawless service. Item arrived exactly as promised.", "date": "2025-10-22" }
  ]
  },
  {
  "id": 12,
  "name": "Siyabonga Mkhize",
  "age": 30,
  "gender": "male",
  "rating": 4.8,
  "totalDeliveries": 51,
  "initialLocation": "Nairobi, Kenya",
  "destination": "Berlin, Germany",
  "travelDate": "2026-01-01",
  "returnDate": "2026-01-14",
  "weight": "15-20",
  "description": "Returning to Berlin after holiday. Plenty of room in checked luggage for medium-sized goods.",
  "experience": "International traveler for 6 years, with a high success rate on cross-continental deliveries.",
  "avatar": "👨‍🎤",
  "email": "siya.mkhize@email.com",
  "phone": "+254 700 333 444",
  "amount": "2200-3500",
  "verified": true,
  "languages": ["Swahili", "English", "German"],
  "preferences": ["Textiles", "Tools", "Educational material"],
  "reviews": [
  { "id": 12, "sender": "Lena B.", "rating": 5, "comment": "Very friendly and the drop-off was easy.", "date": "2025-08-05" }
  ]
  },
  {
  "id": 13,
  "name": "Astrid Nilsson",
  "age": 38,
  "gender": "female",
  "rating": 4.9,
  "totalDeliveries": 92,
  "initialLocation": "Amsterdam, Netherlands",
  "destination": "Rio de Janeiro, Brazil",
  "travelDate": "2025-11-28",
  "returnDate": "2025-12-05",
  "weight": "10-15",
  "description": "On a short vacation. Prefer small, well-packed items that fit easily into my luggage organizer.",
  "experience": "Expert global traveler, focused on efficient and discreet deliveries.",
  "avatar": "👩‍🎨",
  "email": "astrid.n@travel.nl",
  "phone": "+31 6 5432 1098",
  "amount": "1800-2800",
  "verified": true,
  "languages": ["Dutch", "English", "Portuguese"],
  "preferences": ["Tech accessories", "Camera gear", "Small luxury goods"],
  "reviews": [
  { "id": 13, "sender": "Jose V.", "rating": 5, "comment": "Package arrived in perfect condition, zero issues.", "date": "2025-10-18" }
  ]
  },
  {
  "id": 14,
  "name": "Ryan O'Connell",
  "age": 27,
  "gender": "male",
  "rating": 4.1,
  "totalDeliveries": 6,
  "initialLocation": "Los Angeles, USA",
  "destination": "Toronto, Canada",
  "travelDate": "2025-10-30",
  "returnDate": "2025-11-07",
  "weight": "10-20",
  "description": "Road trip with extra trunk space, making the drive between the cities. Can take larger, more bulky items.",
  "experience": "First time using the app but frequently drives the US/Canada route.",
  "avatar": "🧑‍🔧",
  "email": "ryan.oc@road.us",
  "phone": "+1 (555) 777-8888",
  "amount": "1200-2200",
  "verified": false,
  "languages": ["English"],
  "preferences": ["Tools", "Musical instruments (small)", "Sporting goods"],
  "reviews": [
  { "id": 14, "sender": "Sam K.", "rating": 4, "comment": "Excellent communication during the drive. Recommended.", "date": "2025-10-25" }
  ]
  },
  {
  "id": 15,
  "name": "Sofia Petrova",
  "age": 39,
  "gender": "female",
  "rating": 4.6,
  "totalDeliveries": 66,
  "initialLocation": "Moscow, Russia",
  "destination": "Dubai, UAE",
  "travelDate": "2025-12-15",
  "returnDate": "2025-12-22",
  "weight": "5-10",
  "description": "Holiday trip, looking for small, high-value documents or goods for secure transit.",
  "experience": "Many years delivering sensitive parcels across the CIS and Middle East regions.",
  "avatar": "👩‍⚖️",
  "email": "sofia.p@global.ru",
  "phone": "+7 495 123 4567",
  "amount": "1400-2300",
  "verified": true,
  "languages": ["Russian", "English", "Arabic"],
  "preferences": ["Documents", "Jewelry", "High-value electronics"],
  "reviews": [
  { "id": 15, "sender": "Khalid S.", "rating": 5, "comment": "Fast and utterly reliable.", "date": "2025-09-08" }
  ]
  },
  {
  "id": 16,
  "name": "Kenji Tanaka",
  "age": 34,
  "gender": "male",
  "rating": 4.5,
  "totalDeliveries": 30,
  "initialLocation": "Tokyo, Japan",
  "destination": "London, UK",
  "travelDate": "2026-01-20",
  "returnDate": "2026-02-03",
  "weight": "15-20",
  "description": "Can take medium-sized, boxed items. Only acceptable goods for international transit. Prefer pick-up near airport.",
  "experience": "Regularly travels to Europe for conferences and always has available space.",
  "avatar": "👨‍💼",
  "email": "kenji.t@corp.jp",
  "phone": "+81 3 1111 2222",
  "amount": "2800-4500",
  "verified": true,
  "languages": ["Japanese", "English"],
  "preferences": ["Tech gadgets", "Fashion items", "Printed media"],
  "reviews": [
  { "id": 16, "sender": "Oliver H.", "rating": 4, "comment": "Very polite and delivery was on the promised day.", "date": "2025-10-12" }
  ]
  },
  {
  "id": 17,
  "name": "Fatima Benali",
  "age": 25,
  "gender": "female",
  "rating": 4.7,
  "totalDeliveries": 19,
  "initialLocation": "Casablanca, Morocco",
  "destination": "Rome, Italy",
  "travelDate": "2025-11-08",
  "returnDate": "2025-11-15",
  "weight": "5-10",
  "description": "Short European trip. Only small, light items that fit in carry-on or a small backpack.",
  "experience": "Traveled the Mediterranean region extensively for studies and personal travel.",
  "avatar": "👩‍⚕️",
  "email": "fatima.b@mail.ma",
  "phone": "+212 522 34 56 78",
  "amount": "900-1500",
  "verified": true,
  "languages": ["Arabic", "French", "Italian"],
  "preferences": ["Documents", "Small clothes", "Gifts"],
  "reviews": [
  { "id": 17, "sender": "Marco A.", "rating": 5, "comment": "Met me directly at the airport. Very convenient.", "date": "2025-10-02" }
  ]
  },
  {
  "id": 18,
  "name": "Paulo Silva",
  "age": 51,
  "gender": "male",
  "rating": 4.3,
  "totalDeliveries": 40,
  "initialLocation": "Rio de Janeiro, Brazil",
  "destination": "New York, USA",
  "travelDate": "2025-12-05",
  "returnDate": "2025-12-19",
  "weight": "20-25",
  "description": "Traveling for an extended vacation. Plenty of luggage capacity for larger items. No perishable goods.",
  "experience": "Seasoned traveler on this route, understands customs procedures well.",
  "avatar": "👨‍🔧",
  "email": "paulo.s@tour.br",
  "phone": "+55 21 7777 6666",
  "amount": "2500-4000",
  "verified": true,
  "languages": ["Portuguese", "English"],
  "preferences": ["Clothing", "Sporting equipment", "General merchandise"],
  "reviews": [
  { "id": 18, "sender": "Jason R.", "rating": 4, "comment": "A reliable courier for large items. Would use again.", "date": "2025-09-28" }
  ]
  },
  {
  "id": 19,
  "name": "Helena Kovac",
  "age": 36,
  "gender": "female",
  "rating": 4.6,
  "totalDeliveries": 59,
  "initialLocation": "Prague, Czechia",
  "destination": "London, UK",
  "travelDate": "2025-11-25",
  "returnDate": "2025-12-02",
  "weight": "5-10",
  "description": "Quick return trip for work. Only accepting small, non-bulky packages. Prefer meeting at the airport or train station.",
  "experience": "Over 5 years of weekly business travel across central and western Europe.",
  "avatar": "👩‍💼",
  "email": "helena.k@corp.cz",
  "phone": "+420 777 123 456",
  "amount": "1000-1700",
  "verified": true,
  "languages": ["Czech", "English", "German"],
  "preferences": ["High-value documents", "Small samples", "Tech accessories"],
  "reviews": [
  { "id": 19, "sender": "David S.", "rating": 5, "comment": "Fantastic service, perfect for urgent document delivery.", "date": "2025-10-14" }
  ]
  },
  {
  "id": 20,
  "name": "Chinedu Okafor",
  "age": 24,
  "gender": "male",
  "rating": 4.5,
  "totalDeliveries": 12,
  "initialLocation": "Lagos, Nigeria",
  "destination": "Cape Town, South Africa",
  "travelDate": "2026-01-10",
  "returnDate": "2026-01-20",
  "weight": "15-20",
  "description": "Intra-Africa trip with room for larger goods. Happy to coordinate complex logistics.",
  "experience": "Experience with secure transfers between African trade hubs.",
  "avatar": "👨‍🎓",
  "email": "chinedu.o@travel.ng",
  "phone": "+234 810 555 1234",
  "amount": "1500-2500",
  "verified": false,
  "languages": ["Igbo", "English", "Zulu"],
  "preferences": ["Pharmaceuticals", "Small electronics", "Machinery parts"],
  "reviews": [
  { "id": 20, "sender": "Themba Z.", "rating": 5, "comment": "Very trustworthy for valuable cargo on this route.", "date": "2025-10-29" }
  ]
  }
];

  

export const senders = [
  {
    "id": 1,
    "name": "Nohamin Abera",
    "age": "25-30",
    "gender": "female",
    "rating": 4.8,
    "totalDeliveries": 47,
    "initialLocation": "Addis Ababa",
    "destination": "Nairobi",
    "amount": "1000-2000",
    "travelDate": "2025-10-20",
    "returnDate": "2025-10-27",
    "weight": "10-15 kg",
    "description": "I want to send clothes and essentials to my children who live there.",
    "experience": "Frequent Traveler",
    "avatar": "👩‍💼",
    "email": "nohamin.abera@email.com",
    "phone": "+251 911 123456",
    "verified": true,
    "languages": ["English", "Amharic"],
    "preferences": ["Documents", "Clothing"],
    "status": "Urgent"
  },
  {
    "id": 2,
    "name": "Liam O'Connell",
    "age": "31-40",
    "gender": "male",
    "rating": 4.5,
    "totalDeliveries": 12,
    "initialLocation": "London",
    "destination": "New York",
    "amount": "3000-4000",
    "travelDate": "2025-11-05",
    "returnDate": "2025-11-12",
    "weight": "1-5 kg",
    "description": "Sensitive legal documents for a client meeting. Must be hand-delivered.",
    "experience": "Business Traveler",
    "avatar": "👨‍💼",
    "email": "liam.oconnell@email.com",
    "phone": "+44 7700 900301",
    "verified": true,
    "languages": ["English"],
    "preferences": ["Documents", "Small Electronics"],
    "status": "Urgent"
  },
  {
    "id": 3,
    "name": "Sofia Mendoza",
    "age": "18-24",
    "gender": "female",
    "rating": 4.9,
    "totalDeliveries": 89,
    "initialLocation": "São Paulo",
    "destination": "Lisbon",
    "amount": "500-1000",
    "travelDate": "2025-10-25",
    "returnDate": "2025-11-01",
    "weight": "5-10 kg",
    "description": "A box of specialized medical supplies for a family member.",
    "experience": "Student",
    "avatar": "👩‍🎓",
    "email": "sofia.mendoza@email.com",
    "phone": "+55 11 9876 5432",
    "verified": true,
    "languages": ["Portuguese", "Spanish"],
    "preferences": ["Medical Supplies", "Books"],
    "status": "Standard"
  },
  {
    "id": 4,
    "name": "Kwame Ansah",
    "age": "41-50",
    "gender": "male",
    "rating": 4.2,
    "totalDeliveries": 3,
    "initialLocation": "Accra",
    "destination": "Berlin",
    "amount": "2000-3000",
    "travelDate": "2025-12-01",
    "returnDate": "2025-12-15",
    "weight": "15-20 kg",
    "description": "Ghanaian cocoa beans and traditional spices for a trade fair.",
    "experience": "First-time Sender",
    "avatar": "👨‍🌾",
    "email": "kwame.ansah@email.com",
    "phone": "+233 24 0101010",
    "verified": false,
    "languages": ["English", "Twi"],
    "preferences": ["Food Items", "Crafts"],
    "status": "Standard"
  },
  {
    "id": 5,
    "name": "Chloe Dubois",
    "age": "31-40",
    "gender": "female",
    "rating": 5.0,
    "totalDeliveries": 105,
    "initialLocation": "Paris",
    "destination": "Mexico City",
    "amount": "4000+",
    "travelDate": "2025-11-20",
    "returnDate": "2025-11-28",
    "weight": "1-5 kg",
    "description": "High-end jewelry samples for a fashion show. Extremely valuable.",
    "experience": "Luxury Goods Handler",
    "avatar": "👩‍🎨",
    "email": "chloe.dubois@email.com",
    "phone": "+33 6 1234 5678",
    "verified": true,
    "languages": ["French", "English"],
    "preferences": ["Jewelry", "Documents"],
    "status": "Fragile/High Value"
  },
  {
    "id": 6,
    "name": "Javier Herrera",
    "age": "25-30",
    "gender": "male",
    "rating": 4.7,
    "totalDeliveries": 35,
    "initialLocation": "Bogotá",
    "destination": "Madrid",
    "amount": "1000-2000",
    "travelDate": "2025-10-30",
    "returnDate": "2025-11-06",
    "weight": "5-10 kg",
    "description": "Box of family photos and personal items for relocation.",
    "experience": "Routine Sender",
    "avatar": "👨‍🚀",
    "email": "javier.herrera@email.com",
    "phone": "+57 310 234 5678",
    "verified": true,
    "languages": ["Spanish"],
    "preferences": ["Personal Items", "Books"],
    "status": "Standard"
  },
  {
    "id": 7,
    "name": "Fatima Zahrani",
    "age": "51+",
    "gender": "female",
    "rating": 4.1,
    "totalDeliveries": 8,
    "initialLocation": "Casablanca",
    "destination": "Paris",
    "amount": "500-1000",
    "travelDate": "2025-12-05",
    "returnDate": "2025-12-10",
    "weight": "20+ kg",
    "description": "Bulk shipment of traditional Moroccan ceramics and tea sets.",
    "experience": "Local Business Owner",
    "avatar": "👵",
    "email": "fatima.zahrani@email.com",
    "phone": "+212 522 112233",
    "verified": false,
    "languages": ["Arabic", "French"],
    "preferences": ["Ceramics", "Food Items"],
    "status": "Standard"
  },
  {
    "id": 8,
    "name": "Ben Carter",
    "age": "31-40",
    "gender": "male",
    "rating": 4.6,
    "totalDeliveries": 61,
    "initialLocation": "Chicago",
    "destination": "London",
    "amount": "2000-3000",
    "travelDate": "2025-11-15",
    "returnDate": "2025-11-22",
    "weight": "<1 kg",
    "description": "A crucial small electronic circuit board. Handle with extreme care.",
    "experience": "Tech Specialist",
    "avatar": "👨‍💻",
    "email": "ben.carter@email.com",
    "phone": "+1 312 555 0101",
    "verified": true,
    "languages": ["English"],
    "preferences": ["Small Electronics", "Documents"],
    "status": "Fragile/Urgent"
  },
  {
    "id": 9,
    "name": "Aisha Khan",
    "age": "25-30",
    "gender": "female",
    "rating": 4.7,
    "totalDeliveries": 21,
    "initialLocation": "Cairo",
    "destination": "Istanbul",
    "amount": "3000-4000",
    "travelDate": "2025-10-28",
    "returnDate": "2025-11-04",
    "weight": "10-15 kg",
    "description": "Historical artifacts (replicas) for a cultural exhibition.",
    "experience": "Museum Curator",
    "avatar": "👩‍🔬",
    "email": "aisha.khan@email.com",
    "phone": "+20 100 123 4567",
    "verified": true,
    "languages": ["Arabic", "English"],
    "preferences": ["Art/Artifacts", "Books"],
    "status": "Standard"
  },
  {
    "id": 10,
    "name": "Dmitri Volkov",
    "age": "41-50",
    "gender": "male",
    "rating": 3.9,
    "totalDeliveries": 1,
    "initialLocation": "Berlin",
    "destination": "Cape Town",
    "amount": "1000-2000",
    "travelDate": "2025-12-10",
    "returnDate": "2025-12-24",
    "weight": "20+ kg",
    "description": "Winter clothing and a heavy toolkit for a volunteer project.",
    "experience": "Infrequent Sender",
    "avatar": "👨‍🔧",
    "email": "dmitri.volkov@email.com",
    "phone": "+49 30 99887766",
    "verified": false,
    "languages": ["German", "Russian"],
    "preferences": ["Heavy Tools", "Clothing"],
    "status": "Standard"
  },
  {
    "id": 11,
    "name": "Maria Costa",
    "age": "31-40",
    "gender": "female",
    "rating": 4.8,
    "totalDeliveries": 55,
    "initialLocation": "Rio de Janeiro",
    "destination": "Buenos Aires",
    "amount": "500-1000",
    "travelDate": "2025-10-22",
    "returnDate": "2025-10-28",
    "weight": "1-5 kg",
    "description": "A few samples of Brazilian coffee beans for a business partner.",
    "experience": "Small Business Owner",
    "avatar": "👩‍🍳",
    "email": "maria.costa@email.com",
    "phone": "+55 21 3456 7890",
    "verified": true,
    "languages": ["Portuguese"],
    "preferences": ["Food Items", "Samples"],
    "status": "Standard"
  },
  {
    "id": 12,
    "name": "Ethan Smith",
    "age": "18-24",
    "gender": "male",
    "rating": 4.3,
    "totalDeliveries": 9,
    "initialLocation": "Toronto",
    "destination": "Lagos",
    "amount": "4000+",
    "travelDate": "2025-11-01",
    "returnDate": "2025-11-25",
    "weight": "5-10 kg",
    "description": "Expensive, sealed camera lens for a friend. Requires careful handling.",
    "experience": "Photography Enthusiast",
    "avatar": "👨‍🎓",
    "email": "ethan.smith@email.com",
    "phone": "+1 416 112 2334",
    "verified": true,
    "languages": ["English"],
    "preferences": ["Electronics", "Fragile Goods"],
    "status": "Fragile/Urgent"
  },
  {
    "id": 13,
    "name": "Isabelle Leroy",
    "age": "51+",
    "gender": "female",
    "rating": 4.4,
    "totalDeliveries": 17,
    "initialLocation": "Paris",
    "destination": "Tokyo",
    "amount": "3000-4000",
    "travelDate": "2025-11-10",
    "returnDate": "2025-11-17",
    "weight": "10-15 kg",
    "description": "Rare French vintage fashion accessories for a collector.",
    "experience": "Retired Collector",
    "avatar": "👵",
    "email": "isabelle.leroy@email.com",
    "phone": "+33 1 45 67 89 00",
    "verified": true,
    "languages": ["French"],
    "preferences": ["Clothing", "Art/Artifacts"],
    "status": "Standard"
  },
  {
    "id": 14,
    "name": "Kofi Mensah",
    "age": "25-30",
    "gender": "male",
    "rating": 4.8,
    "totalDeliveries": 76,
    "initialLocation": "Johannesburg",
    "destination": "Dubai",
    "amount": "1000-2000",
    "travelDate": "2025-10-29",
    "returnDate": "2025-11-03",
    "weight": "1-5 kg",
    "description": "Marketing materials and banners for a weekend conference.",
    "experience": "Marketing Professional",
    "avatar": "👨‍🎤",
    "email": "kofi.mensah@email.com",
    "phone": "+27 72 334 4556",
    "verified": true,
    "languages": ["English", "Zulu"],
    "preferences": ["Documents", "Display Items"],
    "status": "Urgent"
  },
  {
    "id": 15,
    "name": "Chen Wei",
    "age": "31-40",
    "gender": "female",
    "rating": 4.5,
    "totalDeliveries": 40,
    "initialLocation": "Los Angeles",
    "destination": "Shanghai",
    "amount": "2000-3000",
    "travelDate": "2025-12-15",
    "returnDate": "2026-01-05",
    "weight": "15-20 kg",
    "description": "Prototype consumer electronics for factory testing. Handle with care.",
    "experience": "Engineer",
    "avatar": "👩‍🏭",
    "email": "chen.wei@email.com",
    "phone": "+1 213 555 9876",
    "verified": true,
    "languages": ["Mandarin", "English"],
    "preferences": ["Electronics", "Prototypes"],
    "status": "Fragile"
  },
  {
    "id": 16,
    "name": "Ricardo Alves",
    "age": "41-50",
    "gender": "male",
    "rating": 4.6,
    "totalDeliveries": 22,
    "initialLocation": "Rome",
    "destination": "Buenos Aires",
    "amount": "500-1000",
    "travelDate": "2025-11-08",
    "returnDate": "2025-11-20",
    "weight": "5-10 kg",
    "description": "Small personal items and winter gear for a long stay.",
    "experience": "Traveler",
    "avatar": "👨‍💼",
    "email": "ricardo.alves@email.com",
    "phone": "+39 06 1234 5678",
    "verified": true,
    "languages": ["Italian", "Spanish"],
    "preferences": ["Clothing", "Personal Items"],
    "status": "Standard"
  },
  {
    "id": 17,
    "name": "Naledi Radebe",
    "age": "25-30",
    "gender": "female",
    "rating": 4.9,
    "totalDeliveries": 95,
    "initialLocation": "Dakar",
    "destination": "Amsterdam",
    "amount": "3000-4000",
    "travelDate": "2025-12-03",
    "returnDate": "2025-12-10",
    "weight": "10-15 kg",
    "description": "Textiles and art supplies for a European client.",
    "experience": "Professional Shipper",
    "avatar": "👩‍🎨",
    "email": "naledi.radebe@email.com",
    "phone": "+221 77 123 4567",
    "verified": true,
    "languages": ["French", "Wolof"],
    "preferences": ["Art Supplies", "Textiles"],
    "status": "Urgent"
  },
  {
    "id": 18,
    "name": "Kenji Ito",
    "age": "51+",
    "gender": "male",
    "rating": 4.7,
    "totalDeliveries": 19,
    "initialLocation": "New York",
    "destination": "Shanghai",
    "amount": "4000+",
    "travelDate": "2025-10-21",
    "returnDate": "2025-10-25",
    "weight": "<1 kg",
    "description": "Very small, specialized industrial sensor. Time critical.",
    "experience": "Retired Executive",
    "avatar": "👨‍🔬",
    "email": "kenji.ito@email.com",
    "phone": "+1 917 555 3322",
    "verified": true,
    "languages": ["English", "Japanese"],
    "preferences": ["Small Electronics", "Documents"],
    "status": "Urgent"
  },
  {
    "id": 19,
    "name": "Elsa Schmidt",
    "age": "18-24",
    "gender": "female",
    "rating": 4.0,
    "totalDeliveries": 5,
    "initialLocation": "Berlin",
    "destination": "Nairobi",
    "amount": "500-1000",
    "travelDate": "2025-11-28",
    "returnDate": "2025-12-05",
    "weight": "20+ kg",
    "description": "Books and learning materials for a school donation. Heavy item.",
    "experience": "Student Volunteer",
    "avatar": "👧",
    "email": "elsa.schmidt@email.com",
    "phone": "+49 170 5432100",
    "verified": false,
    "languages": ["German", "English"],
    "preferences": ["Books", "Clothing"],
    "status": "Standard"
  },
  {
    "id": 20,
    "name": "Chiamaka Okoro",
    "age": "31-40",
    "gender": "female",
    "rating": 4.8,
    "totalDeliveries": 33,
    "initialLocation": "Lagos",
    "destination": "Toronto",
    "amount": "2000-3000",
    "travelDate": "2025-11-18",
    "returnDate": "2025-12-01",
    "weight": "10-15 kg",
    "description": "High-value, authentic African fabrics and clothing for sale.",
    "experience": "E-commerce Seller",
    "avatar": "👩‍💼",
    "email": "chiamaka.okoro@email.com",
    "phone": "+234 803 123 4567",
    "verified": true,
    "languages": ["English", "Yoruba"],
    "preferences": ["Textiles", "Clothing"],
    "status": "Standard"
  }
]
;